runtime: nodejs20
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html

env_variables:
  # IS_DEV_MODE: 'False'
  REACT_APP_POKEMON_API_URL: 'https://api-dot-my-test-project-433014.lm.r.appspot.com'
